---
nova_libvirt_images_type: default
nova_libvirt_images_rbd_ceph_conf: "/etc/ceph/ceph.conf"
nova_notification_driver: "nova.openstack.common.notifier.rpc_notifier"
nova_notification_driver_for_ceilometer: "ceilometer.compute.nova_notifier"
nova_notify_on_state_change: vm_and_task_state
nova_network_manager: "nova.network.manager.VlanManager"
nova_scheduler_manager: "nova.scheduler.manager.SchedulerManager"
nova_multi_host: true
nova_security_group_api: nova
nova_scheduler_host_subset_size: 30
nova_firewall_driver: "nova.virt.libvirt.firewall.IptablesFirewallDriver"
nova_conductor_use_local: false

nova_s3_listen_port: 3333
nova_novncproxy_port: 6080
nova_spicehtml5proxy_port: 6082
nova_ec2_listen_port: 8773
nova_osapi_compute_listen_port: 8774
nova_metadata_port: 8775

neutron_ml2_type_drivers: vxlan
neutron_ml2_tenant_network_types: vxlan
neutron_ml2_mechanism_drivers: openvswitch,l2population
neutron_l2_population: true

neutron_auth_strategy: keystone
neutron_enable_security_group: true
neutron_notification_driver: "neutron.openstack.common.notifier.rpc_notifier"
neutron_network_scheduler_driver: "neutron.scheduler.dhcp_agent_scheduler.ChanceScheduler"
neutron_router_scheduler_driver: "neutron.scheduler.l3_agent_scheduler.ChanceScheduler"
neutron_loadbalancer_pool_scheduler_driver: "neutron.services.loadbalancer.agent_scheduler.ChanceScheduler"
neutron_ovs_firewall_driver: "neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver"
neutron_network_auto_schedule: true
neutron_router_auto_schedule: true
neutron_dhcp_agents_per_network: 1
neutron_api_workers: 0
neutron_rpc_workers: 0
neutron_metadata_workers: 4
neutron_tcp_keepidle: 600
neutron_retry_until_window: 30
neutron_backlog: 4096
neutron_metadata_backlog: 2048
neutron_max_header_line: 16384
neutron_use_ssl: false
neutron_vxlan_udp_port: 4789

neutron_notify_nova_on_port_status_changes: true
neutron_notify_nova_on_port_data_changes: true
neutron_dhcp_delete_namespaces: false
neutron_l3_router_delete_namespaces: false
neutron_l3_handle_internal_only_routers: true
neutron_l3_send_arp_for_ha: 3
neutron_core_plugin: ml2
