---
- name: create pacemaker resources for neutron-server
  pcs_resource: command=create name=neutron-server type=systemd:neutron-server clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: neutron

- name: create pacemaker resource for ovs cleanup
  pcs_resource: command=create name=neutron-ovs-cleanup type=ocf:neutron:OVSCleanup group=neutron-agents-pre
  run_once: true
  tags: neutron

- name: create pacemaker resource for netns cleanup
  pcs_resource: command=create name=neutron-netns-cleanup type=ocf:neutron:NetnsCleanup group=neutron-agents-pre
  run_once: true
  tags: neutron

- name: create pacemaker resource for neutron openvswitch agent
  pcs_resource: command=create name=neutron-openvswitch-agent type=systemd:neutron-openvswitch-agent group=neutron-agents
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: neutron

- name: create pacemaker resource for neutron dhcp agent
  pcs_resource: command=create name=neutron-dhcp-agent type=systemd:neutron-dhcp-agent group=neutron-agents
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: neutron

- name: create pacemaker resource for neutron l3 agent
  pcs_resource: command=create name=neutron-l3-agent type=systemd:neutron-l3-agent group=neutron-agents
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  when: use_neutron_l3
  tags: neutron

- name: create pacemaker resource for neutron metadata agent
  pcs_resource: command=create name=neutron-metadata-agent type=systemd:neutron-metadata-agent group=neutron-agents
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: neutron

- name: create pacemaker resource for neutron LBaaS agent
  pcs_resource: command=create name=neutron-lbaas-agent type=systemd:neutron-lbaas-agent group=neutron-agents
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: neutron
