---
use_nova_network: false
use_neutron: true
use_neutron_custom_policy: false
use_neutron_l3: true
use_neutron_ml2: true
use_neutron_ovs: true
use_neutron_cisco: false

neutron_ml2_type_drivers: vxlan
neutron_ml2_tenant_network_types: vxlan
neutron_ml2_mechanism_drivers: openvswitch,l2population
neutron_l2_population: true

neutron_auth_strategy: keystone
neutron_enable_security_group: true
neutron_notification_driver: "neutron.openstack.common.notifier.rpc_notifier"
neutron_network_scheduler_driver: "neutron.scheduler.dhcp_agent_scheduler.ChanceScheduler"
neutron_router_scheduler_driver: "neutron.scheduler.l3_agent_scheduler.ChanceScheduler"
neutron_loadbalancer_pool_scheduler_driver: "neutron.services.loadbalancer.agent_scheduler.ChanceScheduler"
neutron_ovs_firewall_driver: "neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver"
neutron_network_auto_schedule: true
neutron_router_auto_schedule: true
neutron_dhcp_agents_per_network: 1
neutron_api_workers: 0
neutron_rpc_workers: 0
neutron_metadata_workers: 4
neutron_tcp_keepidle: 600
neutron_retry_until_window: 30
neutron_backlog: 4096
neutron_metadata_backlog: 2048
neutron_max_header_line: 16384
neutron_use_ssl: false
neutron_vxlan_udp_port: 4789

neutron_notify_nova_on_port_status_changes: true
neutron_notify_nova_on_port_data_changes: true
neutron_dhcp_delete_namespaces: false
neutron_l3_router_delete_namespaces: false
neutron_l3_handle_internal_only_routers: true
neutron_l3_send_arp_for_ha: 3
neutron_core_plugin: ml2
