---
public_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + primary_if ].ipv4.address }}"
internal_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + private_if ].ipv4.address }}"
horizon_bind_host: "{{ internal_ipaddr }}"
dashboard_first_request_url: "http://{{ horizon_bind_host }}/dashboard"
